stages:
  - push-to-github
  - schedule
  - build

image: ghcr.io/sikalabs/ci

variables:
  DOCKER_BUILDKIT: "1"

push-to-github:
  stage: push-to-github
  script:
    - mkdir -p ~/.ssh
    - cp $GITHUB_PUSH_SSH_KEY_PRIV ~/.ssh/id_rsa
    - chmod 700 -R ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - git remote add github-$CI_PIPELINE_ID git@github.com:ondrejsika/www.git
    - git push github-$CI_PIPELINE_ID $CI_COMMIT_SHA:$CI_COMMIT_BRANCH -f

auto_update_sessions_yml_from_training_crm:
  stage: schedule
  variables:
    GIT_AUTHOR_NAME: SikaLabs[bot]
    GIT_AUTHOR_EMAIL: sikalabsbot@sikalabs.com
    GIT_COMMITTER_NAME: SikaLabs[bot]
    GIT_COMMITTER_EMAIL: sikalabsbot@sikalabs.com
  script:
    - make auto-update-sessions-yml-from-training-crm
    - git remote set-url origin https://ci-bot:$GITLAB_TOKEN_CI_BOT@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
    - git push origin HEAD:$CI_COMMIT_BRANCH
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

.build:
  stage: build
  needs: []
  variables:
    WORKSPACE: .
    SITE_DIR: packages/$SITE
  script:
    - mkdir -p $SITE_DIR/public/api
    - slu static-api version --set-git-clean --set-git-ref $CI_COMMIT_REF_NAME -e CI_PIPELINE_ID=$CI_PIPELINE_ID -e "GITLAB_USER_LOGIN=$GITLAB_USER_LOGIN" -e "CI_COMMIT_TITLE=$CI_COMMIT_TITLE" > $SITE_DIR/public/api/version.json
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build --platform linux/amd64 --build-arg WORKSPACE=$WORKSPACE --build-arg SITE=$SITE --build-arg SITE_DIR=$SITE_DIR -t $CI_REGISTRY_IMAGE/$SITE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE/$SITE .
    - docker push --all-tags $CI_REGISTRY_IMAGE/$SITE

.build-default:
  extends: .build
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule"
      changes:
        - packages/$SITE/**/*
        - packages/data/**/*
        - packages/common/**/*
        - packages/course-landing/**/*
        - Dockerfile
        - ci/docker/*
        - yarn.lock

.build-course-landing:
  extends: .build
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule"
      changes:
        - packages/$SITE/**/*
        - packages/data/training/sessions.yml
        - packages/data/training/recommendations/**/*
        - packages/data/training/pictures/**/*
        - packages/common/**/*
        - packages/course-landing/**/*
        - Dockerfile
        - ci/docker/*
        - yarn.lock

.build-ondrejsika-theme:
  extends: .build
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule"
      changes:
        - packages/$SITE/**/*
        - packages/data/**/*
        - packages/common/**/*
        - packages/ondrejsika-theme/**/*
        - Dockerfile
        - ci/docker/*
        - yarn.lock

.build-sites20:
  extends: .build
  variables:
    WORKSPACE: sites20
    SITE_DIR: sites20/sites/$SITE
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule"
      changes:
        - sites20/sites/$SITE/**/*
        - sites20/themes/**/*
        - sites20/package.json
        - sites20/yarn.lock
        - Dockerfile
        - ci/docker/*

build ondrej-sika.cz:
  extends: .build-ondrejsika-theme
  variables: { SITE: ondrej-sika.cz }

build skolenie.kubernetes.sk:
  extends: .build-course-landing
  variables: { SITE: skolenie.kubernetes.sk }

build training.kubernetes.is:
  extends: .build-course-landing
  variables: { SITE: training.kubernetes.is }

build training.kubernetes.lu:
  extends: .build-course-landing
  variables: { SITE: training.kubernetes.lu }

build skoleni-docker.cz:
  extends: .build-course-landing
  variables: { SITE: skoleni-docker.cz }

build skoleni-kubernetes.cz:
  extends: .build-course-landing
  variables: { SITE: skoleni-kubernetes.cz }

build skoleni-proxmox.cz:
  extends: .build-course-landing
  variables: { SITE: skoleni-proxmox.cz }

build cal-api.sika.io:
  extends: .build-default
  variables: { SITE: cal-api.sika.io }

build sika.blog:
  extends: .build-default
  variables: { SITE: sika.blog }

build static.sika.io:
  extends: .build-default
  variables: { SITE: static.sika.io }

build sikahq.com:
  extends: .build-default
  variables: { SITE: sikahq.com }

build devopsaci-landing:
  extends: .build-sites20
  variables: { SITE: devopsaci-landing }

build devopsaci.cz:
  extends: .build-sites20
  variables: { SITE: devopsaci.cz }

build devopsnews.cz:
  extends: .build-sites20
  variables: { SITE: devopsnews.cz }

build digitalocean.cz:
  extends: .build-sites20
  variables: { SITE: digitalocean.cz }

build hashicorp.cz:
  extends: .build-sites20
  variables: { SITE: hashicorp.cz }

build sikahosting.com:
  extends: .build-sites20
  variables: { SITE: sikahosting.com }

build sikalabs-landing:
  extends: .build-sites20
  variables: { SITE: sikalabs-landing }

build teamsika.com:
  extends: .build-sites20
  variables: { SITE: teamsika.com }
